name: CI

on:
  push:
    branches:
    - main
    paths:
    - 'backend/**.swift'
    - 'backend/**.yml'
    - '.github/workflows/ci.yml'
  pull_request:
    paths:
    - 'backend/**.swift'
    - 'backend/**.yml'
    - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:latest'
    container:
      image: ${{ matrix.image }}
    defaults:
      run:
        working-directory: backend
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Test
      run: swift test
